title: Xavier Olive

include: ['_pages']

markdown: kramdown

highlighter: rouge

kramdown:
    input: GFM

redcarpet:
    extensions:
    - "footnotes"
    - "tables"
    - "no_intra_emphasis"
    - "autolink"

plugins:
  - jekyll/scholar

scholar:

    last_name: Olive
    first_name: Xavier

    style: apa
    locale: en
    source: /extra/
    bibliography: biblio.bib
    bibliography_template: biblio

    replace_strings: true
    join_strings: true

    sort_by: year,month
    order: descending

    coauthors:
        - last: Figuet
          first: Benoit
          url: https://www.zhaw.ch/en/about-us/person/figu/
        - last: Monstein
          first: Raphael
          url: https://www.zhaw.ch/en/about-us/person/mora/
        - last: Morio
          first: Jérôme
          url: https://www.onera.fr/en/staff/jerome-morio
        - last: Schultz
          first: Michael
          url: https://www.unibw.de/lvk-en/chair/team/michael-schultz
        - last: Strohmeier
          first: Martin
          url: https://www.cs.ox.ac.uk/people/martin.strohmeier/
        - last: Sun
          first: Junzi
          url: https://www.junzis.com
        - last: Waltert
          first: Manuel
          url: https://www.zhaw.ch/en/about-us/person/wate/
